version: '3.1'

services:

  db:
    image: postgres
    #restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: test1234
    volumes:
      - ./config/db.sql:/docker-entrypoint-initdb.d/1-init.sql

  app-java:
    build:
      context: .
      args:
        - http_proxy=http://my.proxy.com:80
        - https_proxy=http://my.proxy.com:80
        - HTTP_PROXY=http://my.proxy.com:80
        - HTTPS_PROXY=http://my.proxy.com:80
        - NO_PROXY=my.nexus.server.com
    #restart: always
    ports:
      - 8080:8080
    links:
      - db
    environment:
      POSTGRES_HOST: db
